{ manage-image : Bool
, branch-image : Bool
, root : Bool
, privileged : Bool
, terminal : Bool
, ipc : Bool
, x11 : Bool
, pulseaudio : Bool
, git : Bool
, editor : Bool
, ssh : Bool
, gpg : Bool
, webcam : Bool
, alsa : Bool
, dri : Bool
, kvm : Bool
, tun : Bool
, seccomp : Bool
, selinux : Bool
, setuid : Bool
, ptrace : Bool
, network : Bool
, foreground : Bool
, mount-cwd : Bool
, mount-home : Bool
, mount-run : Bool
, mount-cache : Bool
, auto-update : Bool
, uidmap : Bool
}
